package com.gupao.xing.jian.common.http;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ResultVO implements Serializable {
    private int code;
    private String msg;
    private StudentAndUserinfo data;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public StudentAndUserinfo getData() {
        return data;
    }

    public void setData(StudentAndUserinfo data) {
        this.data = data;
    }

    static class StudentAndUserinfo implements Serializable {
        private List<Student> students;
        private List<UserInfo> userInfos;

        public List<Student> getStudents() {
            return students;
        }

        public void setStudents(List<Student> students) {
            this.students = students;
        }

        public List<UserInfo> getUserInfos() {
            return userInfos;
        }

        public void setUserInfos(List<UserInfo> userInfos) {
            this.userInfos = userInfos;
        }
    }

    static class Student {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.id
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        private Long id;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.name
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        @NotNull(message = "name不能为空")
        @Size(min =1 ,max = 10,message = "name长度范围1-10字符")
        private String name;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.stndeng_class
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        @NotNull(message = "班级当邮箱使用不能为空")
        @Email(message = "邮箱格式不正确")
        private String stndengClass;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.student_num
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        private Integer studentNum;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.create_date
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        @JsonFormat( pattern="yyyy-MM-dd HH:mm:ss")
        private Date createDate;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.update_date
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        @JsonFormat( pattern="yyyy-MM-dd HH:mm:ss")
        private Date updateDate;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column student_t.score
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        private BigDecimal score;

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.id
         *
         * @return the value of student_t.id
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public Long getId() {
            return id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.id
         *
         * @param id the value for student_t.id
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setId(Long id) {
            this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.name
         *
         * @return the value of student_t.name
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public String getName() {
            return name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.name
         *
         * @param name the value for student_t.name
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setName(String name) {
            this.name = name == null ? null : name.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.stndeng_class
         *
         * @return the value of student_t.stndeng_class
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public String getStndengClass() {
            return stndengClass;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.stndeng_class
         *
         * @param stndengClass the value for student_t.stndeng_class
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setStndengClass(String stndengClass) {
            this.stndengClass = stndengClass == null ? null : stndengClass.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.student_num
         *
         * @return the value of student_t.student_num
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public Integer getStudentNum() {
            return studentNum;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.student_num
         *
         * @param studentNum the value for student_t.student_num
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setStudentNum(Integer studentNum) {
            this.studentNum = studentNum;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.create_date
         *
         * @return the value of student_t.create_date
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public Date getCreateDate() {
            return createDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.create_date
         *
         * @param createDate the value for student_t.create_date
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setCreateDate(Date createDate) {
            this.createDate = createDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.update_date
         *
         * @return the value of student_t.update_date
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public Date getUpdateDate() {
            return updateDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.update_date
         *
         * @param updateDate the value for student_t.update_date
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setUpdateDate(Date updateDate) {
            this.updateDate = updateDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column student_t.score
         *
         * @return the value of student_t.score
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public BigDecimal getScore() {
            return score;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column student_t.score
         *
         * @param score the value for student_t.score
         *
         * @mbg.generated Sun Mar 29 16:51:48 CST 2020
         */
        public void setScore(BigDecimal score) {
            this.score = score;
        }
    }


    static class UserInfo implements Serializable {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user_info_t.id
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        private Long id;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user_info_t.name
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        private String name;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user_info_t.sex
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        private String sex;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column user_info_t.age
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        private Short age;

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column user_info_t.id
         *
         * @return the value of user_info_t.id
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public Long getId() {
            return id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user_info_t.id
         *
         * @param id the value for user_info_t.id
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public void setId(Long id) {
            this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column user_info_t.name
         *
         * @return the value of user_info_t.name
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public String getName() {
            return name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user_info_t.name
         *
         * @param name the value for user_info_t.name
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public void setName(String name) {
            this.name = name == null ? null : name.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column user_info_t.sex
         *
         * @return the value of user_info_t.sex
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public String getSex() {
            return sex;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user_info_t.sex
         *
         * @param sex the value for user_info_t.sex
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public void setSex(String sex) {
            this.sex = sex == null ? null : sex.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column user_info_t.age
         *
         * @return the value of user_info_t.age
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public Short getAge() {
            return age;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user_info_t.age
         *
         * @param age the value for user_info_t.age
         *
         * @mbg.generated Sun Mar 29 09:07:03 CST 2020
         */
        public void setAge(Short age) {
            this.age = age;
        }
    }
}
