package com.gupao.xing.jian.app2.userinfo2.service;

import com.github.pagehelper.PageInfo;
import com.gupao.xing.jian.app2.userinfo2.domain.UserInfo2;
import com.gupao.xing.jian.common.exception.MyRuntimeException;

import java.util.List;

public interface IUserInfo2Service {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int insert(UserInfo2 record) throws MyRuntimeException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    UserInfo2 selectByPrimaryKey(Long id);

    PageInfo<UserInfo2> getUserInfo2sByPage();

    List<UserInfo2> getUserInfo2s();
}