package com.gupao.xing.jian.app1.userinfo.mapper;

import com.gupao.xing.jian.app1.userinfo.domain.UserInfo;

import java.util.List;

//@Mapper
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_t
     *
     * @mbg.generated Sun Mar 29 09:07:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_t
     *
     * @mbg.generated Sun Mar 29 09:07:03 CST 2020
     */
    int insert(UserInfo record
    );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_t
     *
     * @mbg.generated Sun Mar 29 09:07:03 CST 2020
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_t
     *
     * @mbg.generated Sun Mar 29 09:07:03 CST 2020
     */
    UserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_t
     *
     * @mbg.generated Sun Mar 29 09:07:03 CST 2020
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info_t
     *
     * @mbg.generated Sun Mar 29 09:07:03 CST 2020
     */
    int updateByPrimaryKey(UserInfo record);

    List<UserInfo> getUserInfos();
}