package com.gupao.xing.jian.app1.student.mapper;

import com.gupao.xing.jian.app1.student.domain.Student;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbg.generated Sun Mar 29 16:51:48 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbg.generated Sun Mar 29 16:51:48 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbg.generated Sun Mar 29 16:51:48 CST 2020
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbg.generated Sun Mar 29 16:51:48 CST 2020
     */
    Student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbg.generated Sun Mar 29 16:51:48 CST 2020
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbg.generated Sun Mar 29 16:51:48 CST 2020
     */
    int updateByPrimaryKey(Student record);

    List<Student> getStudents();
}