package com.gupao.xing.jian.app2.userinfo2.mapper;

import com.gupao.xing.jian.app2.userinfo2.domain.UserInfo2;

import java.util.List;

public interface UserInfo2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int insert(UserInfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int insertSelective(UserInfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    UserInfo2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int updateByPrimaryKeySelective(UserInfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info2_t
     *
     * @mbg.generated Sun Apr 19 18:26:06 CST 2020
     */
    int updateByPrimaryKey(UserInfo2 record);

    List<UserInfo2> getUserInfo2s();
}